[toolchain]
channel = "1.92.0"
# rust-src is required for consistently generating test snapshots with
# `trybuild` that contain snippets of code from the standard library.
components = ["cargo", "rust-src"]
